name: "test-local"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: octokit/request-action@v1.x
      with:
        route: POST /graphql
        query: >
          query {
            user(login: "imjohnbo"){
              name
            }
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
